# Generated by Django 3.1.2 on 2021-02-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Start process', 'Start process'), ('End process', 'End process')], default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Flow',
                'verbose_name_plural': 'Flows',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Pools',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_act', to='bpmn.activitytype')),
                ('current_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_evt', to='bpmn.event')),
                ('next_activity_options', models.ManyToManyField(blank=True, related_name='next_acts_opts', to='bpmn.ActivityType')),
                ('next_event_options', models.ManyToManyField(blank=True, related_name='next_event_opts', to='bpmn.Event')),
            ],
            options={
                'verbose_name_plural': 'Sequences',
            },
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.flow')),
            ],
            options={
                'verbose_name': 'Process Type',
                'verbose_name_plural': 'Process Types',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='INITIALIZING', max_length=255)),
                ('current', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpmn.activity')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bpmn.processtype')),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('pool', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bpmn.pool')),
                ('responsable', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Lanes',
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='sequences',
            field=models.ManyToManyField(to='bpmn.Sequence'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='lane',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bpmn.lane'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bpmn.activitytype'),
        ),
    ]
