# Generated by Django 3.1.2 on 2021-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0002_diagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('prefix', models.CharField(default='', max_length=255)),
                ('path_name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
