# Generated by Django 3.1.2 on 2021-11-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0005_auto_20211107_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='diagram_id',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='diagram_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
