# Generated by Django 3.1.2 on 2022-01-13 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0006_auto_20211107_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='process',
        ),
        migrations.AddField(
            model_name='diagram',
            name='process_type',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bpmn.processtype'),
        ),
    ]
